#!/bin/bash
v1="${SOURCE_BRANCH%-*}"
tor_version=${v1:1}
TOR_VERSION=$(git ls-remote --tags https://git.torproject.org/tor.git | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1)

#
# docker build --build-arg tor_version=${tor_version} -f $DOCKERFILE_PATH -t $IMAGE_NAME .
echo "docker build --build-arg TOR_VERSION=$TOR_VERSION -t $IMAGE_NAME ."
docker build --build-arg TOR_VERSION=$TOR_VERSION -t $IMAGE_NAME .

